services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8500:8500"
    volumes:
      - imports:/app/imports

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data:
  imports: