services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - UPLOAD_FOLDER=/app/imports
      - BACKGROUND_MAX_THREADS=1
      - PHOTON_SERVER_HOST=
      - PHOTON_SERVER_HTTPS=true
      - PHOTON_SERVER_API_KEY=
    ports:
      - "8500:8500"
    volumes:
      - imports:/app/imports

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data:
  imports: