services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - UPLOAD_FOLDER=/app/imports
      - BACKGROUND_MAX_THREADS=5
      - MIN_COUNTRY_VISIT_DURATION_FOR_STATS = 300
      - MIN_CITY_VISIT_DURATION_FOR_STATS = 3600
      - PHOTON_SERVER_HOST=
      - PHOTON_SERVER_HTTPS=true
      - PHOTON_SERVER_API_KEY=
    volumes:
      - imports:/app/imports

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data:
  imports: